apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: main
        ports:
        - containerPort: 80