apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - main.yaml
  - service.yaml

# Version 2023-03-01-1677634140
openapi:
  path: https://github.com/argoproj/argo-schema-generator/raw/2023-03-01-1677634140/schema/argo_all_k8s_kustomize_schema.json

# Version v1.4.0
configurations:
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.4.0/docs/features/kustomize/rollout-transform.yaml
